version: '3.5'
services:
#  app:
#    container_name: springbootdemo
#    hostname: springbootdemo
#    build:
#      dockerfile: ./server/app/Dockerfile
#      context: .
#      args:
#        SPRING_ACTIVE_PROFILE: dev
#    environment:
#      APP_MODE: DEBUG
#      SPRING_ACTIVE_PROFILE: dev
#    ports:
#      - "8080:8080"
#      - "8000:8000"
#    #    volumes:
#    #      - app-backup:/app/files
#    depends_on:
#      - database
  database:
    container_name: springbootdemo
    hostname: springbootdemo
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    restart: always
    #    volumes:
    #      - db-backup:/data
    ports:
      - "5432:5432"

#volumes:
#  app-backup:
#    driver: local
#    driver_opts:
#      type: none
#      device: ${PWD}/backups/app
#      o: bind
#  db-backup:
#    driver: local
#    driver_opts:
#      type: none
#      device: ${PWD}/backups/database
#      o: bind
